#!/bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

LIST_MONITOR=$(xrandr --query | grep " connected" | cut -d" " -f1)
if [ $(echo $LIST_MONITOR | wc -w) -eq 1 ]; then
	bspc monitor -d 1 2 3 4 5
else
	NUM=1
	INCR=4
	for mon in $(xrandr --query | grep " connected" | cut -d" " -f1); do
		bspc monitor $mon -d $(seq $NUM $((NUM + INCR - 1)))
		NUM=$((NUM + INCR))
	done
fi

bspc config border_width 4
bspc config window_gap 13
bspc config focused_border_color "#8A30C9"
bspc config normal_border_color "#2E3440"

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a gnome-calculator state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule --add Pavucontrol state=floating rectangle=1300x600
bspc rule -a Zathura state=tiled
bspc rule -a AppFlowy state=tiled

# Screen saver options
xset -dpms
xset s 300

# Cursor
xsetroot -cursor_name left_ptr

# Polybar config
$HOME/.config/polybar/shades/./launch.sh &

# Lockscreen
xss-lock --ignore-sleep -- betterlockscreen -l --off 2 &

# Window swallowing patch
pgrep bspswallow || bspswallow &

# Get rid of caps lock lol
setxkbmap -option caps:escape &

# My custom startup script
$HOME/.config/startup/./start.sh &

nm-applet &

# Start picom
picom -f
