#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         4
bspc config window_gap          13
bspc config focused_border_color "#8A30C9"
bspc config normal_border_color "#2E3440"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Screen saver options
xset -dpms
xset s 300

# My custom startup script
$HOME/.config/startup/./start.sh &

# Polybar config
$HOME/.config/polybar/shades/./launch.sh &

# Lockscreen
xss-lock --ignore-sleep -- betterlockscreen -l --off 2 &

# Window swallowing patch
pgrep bspswallow || bspswallow &

# Get rid of caps lock lol
setxkbmap -option caps:escape &

# Start picom
picom -f
